### ISSUE TITLE
Shape Error

### ISSUE THREAD

**Issue by sharinganthief** [nielstenboom/recurring-content-detector#38]
just running the defaults 

`import recurring_content_detector as rcd
rcd.detect("<path/>")`

and results with this error

```  1%|▏         | 304/20708 [00:03<03:40, 92.72it/s]
Traceback (most recent call last):
  File "C:\Users\phi\PycharmProjects\pythonProject\main.py", line 2, in <module>
    rcd.detect("Z:\Video\TV Shows\Live Action\Shows\S\Supernatural\Season 6")
  File "C:\Users\phi\AppData\Local\Programs\Python\Python311\Lib\site-packages\recurring_content_detector\__init__.py", line 4, in detect
    return detector.detect(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phi\AppData\Local\Programs\Python\Python311\Lib\site-packages\recurring_content_detector\detector.py", line 238, in detect
    featurevectors.construct_feature_vectors(   
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phi\AppData\Local\Programs\Python\Python311\Lib\site-packages\recurring_content_detector\featurevectors.py", line 108, in construct_feature_vectors
    feature_vector = vector_function(img)
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phi\AppData\Local\Programs\Python\Python311\Lib\site-packages\recurring_content_detector\featurevectors.py", line 75, in color_hist
    result = get_img_color_hist(img, 100)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phi\AppData\Local\Programs\Python\Python311\Lib\site-packages\recurring_content_detector\featurevectors.py", line 70, in get_img_color_hist
    main = main / (image.shape[0] * image.shape[1])
                   ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'shape'

Process finished with exit code 1```

**Comment by nielstenboom** [comment]
Hello, that's unfortunate. Do you have more logs that were printed when you got this error?

**Comment by sharinganthief** [comment]
i think it ended up being a file issue, transcoding broke as well so calling that a day
